### ISSUE TITLE
Landing Page 

### ISSUE THREAD

**Issue by MarwanElkhoudary** [FACG5/unicornz#14]
## Landing Page - Front End 

Landing page is the page which user will see when visit website 
- [ ] index.js
- [ ] style.css

### Component will be use in this page
- [ ] Hero Section
#### Common components
 - [ ] Footer  related to #15
 - [ ] Header related to #15
 - [ ] Main Button related to #15
