### ISSUE TITLE
Work Experience Details 

### ISSUE THREAD

**Issue by MarwanElkhoudary** [FACG5/unicornz#19]
### which Website will be appear after click on work experince card button
 - [ ] index.js
 - [ ] style.css

### Component will be use in this page
- [ ] Company description related to #29 
- [ ] work experience view related to #30 
- [ ] Company Contact related to #32
