### ISSUE TITLE
To Do from 18 Nov. to 22 Nov.

### ISSUE THREAD

**Issue by hshahwan** [FACG5/unicornz#77]
Hey Team,
@ahmad1091 @MarwanElkhoudary @amd711 @donia98 
So proud of you actually, you decided to learn a new skill and you are making progress.
React and Sequilze not easy but I trust of your ability so let's make small schedule form this week.

## NOTE:
We have delivered the MVP at the end of this week. 22 Nov.
 - [ ] Setup heroku #59 
- [ ] Questionare [ front and back end ] . #20 
- [ ] Dashboard [ front and back end ] . #53 #11 
- [ ] work experinces [ front and back end ] . #6 
- [ ] log in and sign up  [font and back end ] #71 #72 #73 

please assign your self in the issues that you work on it and show us more progress: D
